### PR TITLE
fixed the html problem 

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
Where navigating from 1 Html file to another would cause erroneous behavior

### CODE REVIEW

**Comment by omsmith** [comment]
What was the erroneous behaviour?

**Comment by jstefaniuk-d2l** [comment]
"Error: Invariant Violation: findComponentRoot(..., .0.2.0.0.1.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``."

After getting this error all sorts of weird things would happen, sometimes the fileviewer wouldn't switch to the next item (like if you clicked on an image), I once had it where it stayed on the webpage after clicking the image, but it replaced my test google logo in the html file with the Kitchener picture.

**Comment by omsmith** [comment]
It would be great if you described that a little more in the commit message (provide a short message < 80 chars on the 1st line, and then describe it a bit more on the 3rd line+)

You can use `git commit --amend` to edit it.

**Comment by jstefaniuk-d2l** [comment]
(I kind of screwed up that git amend, but I'll try to do more detailed commit messages in the future)

**Comment by omsmith** [comment]
I can help you clear it up after I'm off this call.

**Comment by jstefaniuk-d2l** [comment]
Ok, sounds good!

**Comment by omsmith** [comment]
Not an expert in the area, but thanks for cleaning that up :)

**Pull request merged**
