### PR TITLE
make change to allow image to be bound by height in chrome

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
https://github.com/Brightspace/activity-viewer/pull/63
https://github.com/Brightspace/sequence-viewer/pull/85

### CODE REVIEW

**Comment by CodeBaboon** [comment]
LGTM

**Comment by Surekh** [comment]
Issue - Sample app no longer loads files after this change.

**Comment by CodeBaboon** [comment]
I have a fix for the sample app styling to accommodate this change but I don't seem to have permission to push it to Jeff's repo. I'll create a new PR for the fix to the sample.

**Comment by Surekh** [comment]
[ ] - Issue: Sample App no longer displays content in Safari browser

**Comment by jstefaniuk-d2l** [comment]
I'll look into this as soon as I get the activity-viewer tests working with karma

**Comment by Surekh** [comment]
LGTM!

**Pull request merged**
