### PR TITLE
Added base lang files, set up language builder

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
@dlockhart look good?

**Comment by dlockhart** [comment]
This doesn't seem quite right. The compiled language files are being committed to source control, so you're ending up with just a bunch of duplicate files. Typically how the language builder is used is to compile the language files along with the rest of the application to a "dist" distribution directory (not in source control), which then ultimately ends up on a CDN. But because this is a component and not an application, that doesn't work -- there's nowhere to publish it to.

What I might suggest instead is this: Don't use the language builder, since it's going to generate a bunch of duplicate files that you don't need. Instead, do the resolution for each term at runtime when it's asked for. For example, since the term "Download" likely doesn't have any regional deviations at this point, you'll likely only need the base language files (e.g. "en.json", "ar.json", etc.). But let's say you did have a regional variation in "en-CA.json". So when the term is asked for in the "en-CA" locale, you first see if it's in "en-CA.json", and if not, look in "en.json". Similarly if a request comes in for the "en-ABC" locale, you don't recognize the region so go right to "en.json".

I'm probably doing a terrible job of explaining this but essentially put everything in the base language files, the only put regional overrides in the others (which you'll likely have none at this point), load up all the files and then "resolve" the term value at runtime.

**Comment by jstefaniuk-d2l** [comment]
@dlockhart Hmm, this seems like it could possibly be overkill for the task at hand (Seeing as we only have one langterm at the moment, and may never have more than a few)

Maybe I should just change it back to the way it was (but add the base files to the folder as well)

**Comment by dlockhart** [comment]
Sure. You could also change it back to the way it was -- just base files -- and then no matter what locale they request, just strip the end part off (so "en-CA" becomes "en") and use that.

**Comment by jstefaniuk-d2l** [comment]
The one problem would be that the zh-ch and zh-tw are slightly different characters

**Comment by dlockhart** [comment]
Right, yeah you could treat that as a special case for now and _not_ strip off the regional tag.

**Pull request closed without merging**
